# Generated by Django 4.2.7 on 2025-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_is_online_device_last_seen_device_sys_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
