# Generated by Django 4.2.7 on 2025-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_device_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('host', models.CharField(help_text='IP address or hostname to probe', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('packet_loss', models.FloatField(blank=True, null=True)),
                ('upstream_mbps', models.FloatField(blank=True, null=True)),
                ('downstream_mbps', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
