# Generated by Django 4.2.7 on 2025-10-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_device_custom_oids_device_poll_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
