# Generated by Django 5.2.6 on 2025-10-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customdashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='extra',
        ),
        migrations.DeleteModel(
            name='CustomDashboard',
        ),
    ]
