# Generated by Django 4.2.7 on 2025-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_metric_extra_delete_customdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., GigabitEthernet0/1', max_length=100)),
                ('device_name', models.CharField(help_text='Name of the switch/router', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('capacity_mbps', models.IntegerField(default=1000, help_text='Port speed in Mbps')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='up', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('bps_in', models.BigIntegerField(default=0)),
                ('bps_out', models.BigIntegerField(default=0)),
                ('utilization_in', models.FloatField(default=0.0)),
                ('utilization_out', models.FloatField(default=0.0)),
                ('errors_in', models.IntegerField(default=0)),
                ('errors_out', models.IntegerField(default=0)),
            ],
        ),
    ]
