# Generated by Django 4.2.7 on 2026-01-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpu_load',
            field=models.FloatField(default=0.0, help_text='Current CPU Load %'),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_load',
            field=models.FloatField(default=0.0, help_text='Current Memory Used %'),
        ),
        migrations.AddField(
            model_name='device',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Device Temperature (C)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='uplink_capacity',
            field=models.CharField(default='10 Gbps', help_text='Uplink Connection Speed', max_length=50),
        ),
        migrations.AddField(
            model_name='isp',
            name='is_flapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='isp',
            name='plan_download_mbps',
            field=models.FloatField(default=100.0, help_text='Plan Download Speed Limit'),
        ),
        migrations.AddField(
            model_name='isp',
            name='plan_upload_mbps',
            field=models.FloatField(default=100.0, help_text='Plan Upload Speed Limit'),
        ),
        migrations.AddField(
            model_name='isp',
            name='provider_image',
            field=models.CharField(blank=True, help_text='Path to provider logo image', max_length=255),
        ),
        migrations.AddField(
            model_name='port',
            name='critical_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='is_flapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='port',
            name='packet_drops',
            field=models.FloatField(default=0.0, help_text='Percentage of packet drops'),
        ),
        migrations.AddField(
            model_name='zone',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Current humidity percentage', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Current temperature in Celsius', null=True),
        ),
    ]
