# Generated by Django 5.2.6 on 2026-02-22 10:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_device_cpu_load_device_memory_load_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('cpu_usage', 'CPU Usage %'), ('memory_usage', 'Memory Usage %'), ('temperature', 'Temperature °C'), ('network_in', 'Network In Mbps'), ('network_out', 'Network Out Mbps')], max_length=30)),
                ('threshold_value', models.FloatField(help_text='Trigger alert when metric exceeds this value')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning')], default='warning', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['metric_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='isp',
            options={'verbose_name': 'ISP', 'verbose_name_plural': 'ISPs'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['device_name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=161, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='metric',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='idx_alert_status_severity'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', 'status'], name='idx_alert_device_status'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='idx_alert_created'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status', 'created_at'], name='idx_alert_sev_stat_date'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['-created_at'], name='idx_audit_created'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['event_type'], name='idx_audit_event_type'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_online'], name='idx_device_online'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='idx_device_active'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='idx_device_ip'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='idx_device_type'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active', 'is_online'], name='idx_device_active_online'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['device', '-timestamp'], name='idx_metric_device_time'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['-timestamp'], name='idx_metric_timestamp'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['device', 'timestamp'], name='idx_metric_dev_ts_asc'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['key'], name='idx_zone_key'),
        ),
        migrations.AlterUniqueTogether(
            name='alertthreshold',
            unique_together={('metric_name', 'severity')},
        ),
    ]
