# Generated by Django 5.2.6 on 2026-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alertthreshold_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('server', 'Server Room'), ('public', 'Public Area'), ('operations', 'Operations'), ('critical', 'Critical Infrastructure'), ('storage', 'Storage Area')], default='operations', max_length=50),
        ),
    ]
