# Generated by Django 5.2.6 on 2026-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_zone_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='port_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
