# Generated by Django 4.2.7 on 2026-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_port_device_ip_port_port_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ups_battery_level',
            field=models.FloatField(blank=True, help_text='UPS Battery Level %', null=True),
        ),
    ]
