# Generated by Django 4.2.7 on 2026-04-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_device_ups_battery_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['device', 'name']},
        ),
        migrations.RemoveField(
            model_name='port',
            name='device_ip',
        ),
        migrations.RemoveField(
            model_name='port',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='port',
            name='port_ip',
        ),
        migrations.AddField(
            model_name='port',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='api.device'),
        ),
        migrations.AddField(
            model_name='port',
            name='port_number',
            field=models.IntegerField(default=0),
        ),
    ]
