# Generated by Django 4.2.7 on 2026-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_port_options_remove_port_device_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='network_in',
            field=models.FloatField(default=0.0, help_text='Current Inbound Mbps'),
        ),
        migrations.AddField(
            model_name='device',
            name='network_out',
            field=models.FloatField(default=0.0, help_text='Current Outbound Mbps'),
        ),
    ]
