# Generated by Django 4.2.7 on 2026-04-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_device_network_in_device_network_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='network_in',
        ),
        migrations.RemoveField(
            model_name='device',
            name='network_out',
        ),
        migrations.AddField(
            model_name='metric',
            name='isp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.isp'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.device'),
        ),
    ]
