# Generated by Django 4.2.7 on 2026-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_device_network_in_remove_device_network_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='network_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='network_out',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['isp', '-timestamp'], name='idx_metric_isp_time'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['isp', 'timestamp'], name='idx_metric_isp_ts_asc'),
        ),
    ]
